// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package assets

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed ChivoMono-ExtraBold.ttf
var resourceChivoMonoExtraBoldTtfData []byte

var ResourceChivoMonoExtraBoldTtf = &fyne.StaticResource{
	StaticName:    "ChivoMono-ExtraBold.ttf",
	StaticContent: resourceChivoMonoExtraBoldTtfData,
}
