// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed ChivoMono-ExtraBold.ttf
var resourceChivoMonoExtraBoldTtfData []byte
var resourceChivoMonoExtraBoldTtf = &fyne.StaticResource{
	StaticName:    "ChivoMono-ExtraBold.ttf",
	StaticContent: resourceChivoMonoExtraBoldTtfData,
}
